{
  "name": "nexo-atomico",
  "version": "1.0.0",
  "description": "Nexo Atomico App",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "@capacitor/android": "^6.0.0",
    "@capacitor/core": "^6.0.0"
  },
  "devDependencies": {
    "@capacitor/cli": "^6.0.0",
    "typescript": "^5.0.0"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}
